### ISSUE TITLE
Can't override default index view

### ISSUE THREAD

**Issue by gbrindisi** [syrusakbary/Flask-SuperAdmin#14]
As stated here: https://github.com/SyrusAkbary/Flask-SuperAdmin/blob/master/flask_superadmin/base.py#L198

I am doing this:

``` python
class MyHomeView(AdminIndexView):
    @expose('/')
    def index(self):
        return render_template('adminhome.html')

admin = Admin(index_view=MyHomeView)
admin.init_app(app)
```

What I get:

```
Traceback (most recent call last):
  File "./run.py", line 3, in <module>
    from test import app
  File "/Users/g/test/test/__init__.py", line 48, in <module>
    admin.init_app(app)
  File "/Users/g/test/lib/python2.7/site-packages/flask_superadmin/base.py", line 448, in init_app
    app.register_blueprint(view.create_blueprint(self))
TypeError: unbound method create_blueprint() must be called with MyHomeView instance as first argument (got Admin instance instead)
```

**Comment by termax** [comment]
Thanks you saved me ... just spent 2 days trying to figure out what am i doing wrong :)
